version: '3'

services:
  backend:
    container_name: cuembyapp
    restart: always
    build: .
    ports: -"8080:8080"
    links: -mongo
    volumes: -.:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
