version: '3'

services:
  backend:
    container_name: cuembyapp
    restart: always
    build: .
    ports: -"5000:8081"
    links: -mongo
    volumes: -.:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports: -"27017:27017"
